# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db9698d96b75d7b2cdf468a1ea4ee001e6ecf3bc63efa488c8bb28d6a5052aa3b565ba122ada5cdce87757fbf4fc997fca976e79765875b99cd1f7e690f90c2a

test:
  secret_key_base: 20692a150bb9681fa73d1b111f24fbd712f316cc5cac6b0371b0d0853c5ee45d462bee0f72a22f433f9edbdd09ccf629b3397f4b4046bb42065e3d8bcaaab8da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
